# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Achievement.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'Achievement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41\x63hievement.proto\x12\tDC.Packet\"K\n\x1bSCOMPLETED_ACHIEVEMENT_INFO\x12\x15\n\rachievementID\x18\x01 \x01(\t\x12\x15\n\rcompletedTime\x18\x02 \x01(\x04\"A\n\x1bSACHIEVEMENT_OBJECTIVE_INFO\x12\x13\n\x0bobjectiveId\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r\"r\n\x1dSUNCOMPLETED_ACHIEVEMENT_INFO\x12\x15\n\rachievementID\x18\x01 \x01(\t\x12:\n\nobjectives\x18\x03 \x03(\x0b\x32&.DC.Packet.SACHIEVEMENT_OBJECTIVE_INFO\"<\n\x1aSACHIEVEMENT_PROGRESS_INFO\x12\x0b\n\x03\x61ll\x18\x01 \x01(\x05\x12\x11\n\tcompleted\x18\x02 \x01(\x05\"\xc0\x01\n\x15SS2C_ACHIEVEMENTS_NOT\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x45\n\x15\x63ompletedAchievements\x18\x02 \x03(\x0b\x32&.DC.Packet.SCOMPLETED_ACHIEVEMENT_INFO\x12P\n\x1euncompletedUpdatedAchievements\x18\x03 \x03(\x0b\x32(.DC.Packet.SUNCOMPLETED_ACHIEVEMENT_INFO\"D\n\x1aSC2S_ACHIEVEMENTS_LIST_REQ\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x16\n\x0e\x61\x63hievementIds\x18\x02 \x03(\t\"\xa1\x02\n\x1aSS2C_ACHIEVEMENTS_LIST_RES\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x45\n\x15\x63ompletedAchievements\x18\x02 \x03(\x0b\x32&.DC.Packet.SCOMPLETED_ACHIEVEMENT_INFO\x12P\n\x1euncompletedUpdatedAchievements\x18\x03 \x03(\x0b\x32(.DC.Packet.SUNCOMPLETED_ACHIEVEMENT_INFO\x12\x1d\n\x15invalidAchievementIds\x18\x04 \x03(\t\x12;\n\x0cprogressInfo\x18\x05 \x01(\x0b\x32%.DC.Packet.SACHIEVEMENT_PROGRESS_INFOB(\n\x17\x63om.packets.achievementB\x0b\x61\x63hievementP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Achievement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.packets.achievementB\013achievementP\000'
  _globals['_SCOMPLETED_ACHIEVEMENT_INFO']._serialized_start=32
  _globals['_SCOMPLETED_ACHIEVEMENT_INFO']._serialized_end=107
  _globals['_SACHIEVEMENT_OBJECTIVE_INFO']._serialized_start=109
  _globals['_SACHIEVEMENT_OBJECTIVE_INFO']._serialized_end=174
  _globals['_SUNCOMPLETED_ACHIEVEMENT_INFO']._serialized_start=176
  _globals['_SUNCOMPLETED_ACHIEVEMENT_INFO']._serialized_end=290
  _globals['_SACHIEVEMENT_PROGRESS_INFO']._serialized_start=292
  _globals['_SACHIEVEMENT_PROGRESS_INFO']._serialized_end=352
  _globals['_SS2C_ACHIEVEMENTS_NOT']._serialized_start=355
  _globals['_SS2C_ACHIEVEMENTS_NOT']._serialized_end=547
  _globals['_SC2S_ACHIEVEMENTS_LIST_REQ']._serialized_start=549
  _globals['_SC2S_ACHIEVEMENTS_LIST_REQ']._serialized_end=617
  _globals['_SS2C_ACHIEVEMENTS_LIST_RES']._serialized_start=620
  _globals['_SS2C_ACHIEVEMENTS_LIST_RES']._serialized_end=909
# @@protoc_insertion_point(module_scope)
