# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: S_Session.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'S_Session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fS_Session.proto\x12\tDC.Packet\"9\n\x16SD2S_SESSION_HELLO_REQ\x12\x11\n\tprocessId\x18\x01 \x01(\x05\x12\x0c\n\x04port\x18\x02 \x01(\x05\";\n\x16SS2D_SESSION_HELLO_RES\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x11\n\tsessionId\x18\x02 \x01(\x03\"/\n\x1aSD2S_SESSION_RECONNECT_REQ\x12\x11\n\tsessionId\x18\x01 \x01(\x03\",\n\x1aSS2D_SESSION_RECONNECT_RES\x12\x0e\n\x06result\x18\x01 \x01(\r\"\x16\n\x14SS2D_SESSION_DIE_NOTB$\n\x15\x63om.packets.s_sessionB\ts_sessionP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'S_Session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.packets.s_sessionB\ts_sessionP\000'
  _globals['_SD2S_SESSION_HELLO_REQ']._serialized_start=30
  _globals['_SD2S_SESSION_HELLO_REQ']._serialized_end=87
  _globals['_SS2D_SESSION_HELLO_RES']._serialized_start=89
  _globals['_SS2D_SESSION_HELLO_RES']._serialized_end=148
  _globals['_SD2S_SESSION_RECONNECT_REQ']._serialized_start=150
  _globals['_SD2S_SESSION_RECONNECT_REQ']._serialized_end=197
  _globals['_SS2D_SESSION_RECONNECT_RES']._serialized_start=199
  _globals['_SS2D_SESSION_RECONNECT_RES']._serialized_end=243
  _globals['_SS2D_SESSION_DIE_NOT']._serialized_start=245
  _globals['_SS2D_SESSION_DIE_NOT']._serialized_end=267
# @@protoc_insertion_point(module_scope)
